Ndaru/moderation
Shopeephobia/amnesicure pull request #23
Opened 2022-12-02 17:17 UTC by stndaru

2022-12-02 19:14 UTC, determinedguy requested changes
Coba di-*review* dulu komentar yang udah gue kasih, kali aja ada yang gue juga kelupaan atau *miss* (mohon maklum, *review* di jam 2 💀). 🙏🏼

2022-12-02 19:14 UTC, determinedguy commented on deck/urls.py
> +    path('admin/requests', fetch_requests, name='fetch_requests'),
Ini yang `admin/` berarti *intended access* URL-nya `server.com/deck/admin/` kah?

2022-12-02 19:14 UTC, determinedguy commented on deck/urls.py
> +    path('admin/requests/verify/<id>', verify_request, name='verify_deck'),
Ini parameter `<id>`-nya udah teruji bisa diakses dan benar?
Soalnya yang gue tahu, dia formatnya `<int:pk>` dan variabelnya ikut nama yang ada di *method* di `views.py`.
```suggestion
    path('admin/requests/verify/<int:pkPub>', verify_request, name='verify_deck'),
```

2022-12-02 19:14 UTC, determinedguy commented on deck/urls.py
> +    path('admin/requests/reject/<id>', reject_request, name='reject_deck'),
Sama seperti sebelumnya.
```suggestion
    path('admin/requests/reject/<int:pkPub>', reject_request, name='reject_deck'),
```

2022-12-02 19:14 UTC, determinedguy commented on deck/urls.py
>  ]
Fungsi `create_request` belum diintegrasikan kah?

2022-12-02 19:14 UTC, determinedguy commented on deck/views.py
> +        deck_request = PublishPrivateDeck(user=request.user, private_deck=private_deck, public_deck=public_deck, isVerified=False)
Isi `isVerfied` sebenarnya nggak perlu di-*define*, sih. *Default value*-nya kan `False`, hehe.

2022-12-02 19:14 UTC, determinedguy commented on deck/views.py
> +    'id' : 1
Berarti variabel `id` berfungsi sebagai status `True`/`False` gitu ya?

2022-12-03 01:20 UTC, stndaru commented on deck/urls.py
> +    path('admin/requests', fetch_requests, name='fetch_requests'),
iya kak, meski sedikit lebih ribet tapi buat nunjukin itu buat admin access. tapi agak aneh dikit sih kak.

2022-12-03 01:20 UTC, stndaru commented on deck/urls.py
> +    path('admin/requests/verify/<id>', verify_request, name='verify_deck'),
udah diganti kak 🙏

2022-12-03 01:26 UTC, stndaru commented on deck/urls.py
>  ]
udah diintegrasiin di commit terbaru kak

2022-12-03 01:26 UTC, stndaru commented on deck/views.py
> +        deck_request = PublishPrivateDeck(user=request.user, private_deck=private_deck, public_deck=public_deck, isVerified=False)
gapapa kak hehe

2022-12-03 01:26 UTC, stndaru commented on deck/views.py
> +    'id' : 1
iya kak

2022-12-03 04:29 UTC, determinedguy commented on deck/urls.py
> +    path('admin/requests', fetch_requests, name='fetch_requests'),
LGTM.

2022-12-03 04:29 UTC, determinedguy commented on deck/urls.py
>  ]
LGTM.

2022-12-03 04:32 UTC, determinedguy approved these changes
LGTM, well done. 👍🏼

2022-12-03 04:32 UTC, merged